services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $appClientId: '%env(APP_CLIENT)%'
            $appSecret: '%env(APP_SECRET)%'
            $appStoreSecret: '%env(APPSTORE_APP_SECRET)%'
            Psr\Log\LoggerInterface $logger: '@monolog.logger.app'

    monolog.logger.app:
        class: Monolog\Logger
        arguments: ['app']
        calls:
            - [pushHandler, ['@app_logs']]

    app_logs:
        class: Monolog\Handler\StreamHandler
        arguments: ['%kernel.logs_dir%/dev.log', 'debug']
        tags:
            - { name: monolog.logger, channel: app }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Registration of external services
    DreamCommerce\Component\Common\Http\GuzzleClient:

    DreamCommerce\Component\ShopAppstore\Api\Http\ShopClient:
