framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\CreateExternalPaymentMessage': async
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: ~

