framework:
    messenger:
        serializer:
            default_serializer: App\Messenger\Serializer\ExceptionContextMinimalSerializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                serializer: App\Messenger\Serializer\ExceptionContextMinimalSerializer
                options:
                    queue_name: async
                    auto_setup: true
            failed:
                dsn: 'doctrine://default?queue_name=failed'
                serializer: App\Messenger\Serializer\ExceptionContextMinimalSerializer

        routing:
            'App\Message\CreatePaymentMessage': async
            'App\Message\DeletePaymentMessage': async
            'App\Message\UpdatePaymentMessage': async
            'App\Message\CreatePaymentChannelMessage': async
            'App\Message\UpdatePaymentChannelMessage': async
            'App\Message\DeletePaymentChannelMessage': async
        default_bus: messenger.bus.default

        failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - App\Messenger\Middleware\ApiExceptionMiddleware
                    - App\Messenger\Middleware\MessengerLoggingMiddleware
