monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/dev.log"
            max_files: 10
            level: debug
            channels: ["!event", "!doctrine", "!console"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        prod:
            type: rotating_file
            path: "%kernel.logs_dir%/prod.log"
            max_files: 30
            level: error
