monolog:
    channels: ['app']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/prod.log"
            level: critical
            channels: ["!event", "!doctrine"]

        app_logs:
            type: stream
            path: "%kernel.logs_dir%/dev.log"
            level: debug
            channels: ['app']

        debug_file:
            type: stream
            path: "%kernel.logs_dir%/debug.log"
            level: debug
            channels: ["!app", "!event"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
